cart/urls.py
from django.urls import path
from . import views
app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:listing_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:listing_id>/', views.cart_remove, 
                                     name='cart_remove'),
]

cupcake/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('listings/', include('listings.urls')),
    path('orders/', include('orders.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms
PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
        choices=PRODUCT_QUANTITY_CHOICES,
        coerce=int,
        widget=forms.TextInput(attrs={'class': 'form-control'}))
    override = forms.BooleanField(required=False,
                                  initial=False,
                                  widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from menu.models import Menu
from .cart import Cart
from .forms import CartAddProductForm

@require_POST
def cart_add(request, listing_id):
    cart = Cart(request)
    product = get_object_or_404(Menu, pk=listing_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product,
                 quantity=cd['quantity'],
                 override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, listing_id):
    cart = Cart(request)
    product = get_object_or_404(Menu, pk=listing_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/detail.html', {'cart': cart})


def checkout(request):
    cart = Cart(request)
    return render(request, 'cart/checkout.html', {'cart': cart})

templates/cart/cart.html
{% load static %}
<h1>Your shopping cart</h1>
<table class="cart">
  <thead>
    <tr>
      <th>Image</th>
      <th>Product</th>
      <th>Quantity</th>
      <th>Remove</th>
      <th>Unit price</th>
      <th>Price</th>
    </tr>
  </thead>
  <tbody>
    {% for item in cart %}
      {% with product=item.product %}
        <tr>
          <td>
            <a href="{{ product.get_absolute_url }}">
              <img src="{% if product.image %}{{ product.image.url }}
              {% else %}{% static "img/no_image.png" %}{% endif %}">
            </a>
          </td>
          <td>{{ product.name }}</td>
          <td>
            <form action="{% url "cart:cart_add" product.id %}" method="post">
              {{ item.update_quantity_form.quantity }}
              {{ item.update_quantity_form.override }}
              <input type="submit" value="Update">
              {% csrf_token %}
            </form>
          </td>
          <td>
            <form action="{% url "cart:cart_remove" product.id %}" method="post">
              <input type="submit" value="Remove">
              {% csrf_token %}
            </form>
          </td>
          <td class="num">${{ item.price }}</td>
          <td class="num">${{ item.total_price }}</td>
        </tr>
      {% endwith %}
    {% endfor %}
    <tr class="total">
      <td>Total</td>
      <td colspan="4"></td>
      <td class="num">${{ cart.get_total_price }}</td>
    </tr>
  </tbody>
</table>
<p class="text-right">
  <a href="{% url "shop:product_list" %}" class="button
  light">Continue shopping</a>
  <a href="{% url "orders:order_create" %}" class="button">
    Checkout
  </a>
</p>

templates/cart/created.html
{% load static %}
<!DOCTYPE html>
<!--[if IE 7]><html class="ie ie7"><![endif]-->
<!--[if IE 8]><html class="ie ie8"><![endif]-->
<!--[if IE 9]><html class="ie ie9"><![endif]-->
<html lang="en">
  <!-- Mirrored from nouthemes.net/html/bakery/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 27 Aug 2020 10:03:34 GMT -->
  <head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="format-detection" content="telephone=no" />
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <link href="apple-touch-icon.png" rel="apple-touch-icon" />
    <link href="favicon.png" rel="icon" />
    <meta name="author" content="#{author}" />
    <meta name="keywords" content="#{keyword}" />
    <meta name="description" content="#{description}" />
    <title>Taiping Bakery | Your #1 Choice</title>
    <!-- Fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Libre+Baskerville:400,400i,700%7CPacifico%7CVarela+Round%7CPoppins"
      rel="stylesheet"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/font-awesome/css/font-awesome.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/jquery-bar-rating/dist/themes/fontawesome-stars.css' %}"
    />
    <link rel="stylesheet" href="{% static 'plugins/ps-icon/ps-icon.css' %}" />
    <!-- CSS Library-->
    <link
      rel="stylesheet"
      href="{% static 'plugins/bootstrap/dist/css/bootstrap.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/owl-carousel/assets/owl.carousel.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/jquery-bar-rating/dist/themes/fontawesome-stars.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/Magnific-Popup/dist/magnific-popup.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/jquery-ui/jquery-ui.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/slick/slick/slick.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/lightGallery-master/dist/css/lightgallery.min.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/revolution/css/settings.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/revolution/css/layers.css' %}"
    />
    <link
      rel="stylesheet"
      href="{% static 'plugins/revolution/css/navigation.css' %}"
    />
    <!-- Custom-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <!--HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries-->
    <!--WARNING: Respond.js doesn't work if you view the page via file://-->
    <!--[if lt IE 9
      ]><script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script
    ><![endif]-->
  </head>
  <!--[if IE 7]><body class="ie7 lt-ie8 lt-ie9 lt-ie10"><![endif]-->
  <!--[if IE 8]><body class="ie8 lt-ie9 lt-ie10"><![endif]-->
  <!--[if IE 9]><body class="ie9 lt-ie10"><![endif]-->
  <body class="page-init">
    <div class="header--sidebar"></div>
    <header class="header" data-responsive="1199">
      <div class="header__top">
        <div class="container">
          <div class="row">
            <div class="col-lg-8 col-md-7 col-sm-12 col-xs-12">
              <p>
                144-146, Jalan Taming Sari, 34000 Taiping, Perak - Hotline:
                05-8073354
              </p>
            </div>
          </div>
        </div>
      </div>
      <nav class="navigation">
        <div class="container">
          <div class="menu-toggle"><span></span></div>
          <div class="navigation__left">
            <ul class="menu menu--left">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li><a href="{% url 'about' %}">About</a></li>
              <li><a href="{% url 'vault' %}">Cake's Vault</a></li>
            </ul>
          </div>
          <a class="ps-logo" href="{% url 'index' %}"
            ><img src="{% static 'images/logo-1.png' %}" alt=""
          /></a>
          <div class="navigation__right">
            <ul class="menu menu--right">
              <li class="menu-item-has-children">
                <a href="blog-listing.html">Blogs</a>
                <ul class="sub-menu">
                  <li class="menu-item-has-children">
                    <a href="blog-detail.html">Blog Detail</a>
                    <ul class="sub-menu">
                      <li><a href="#">Sample Menu #1</a></li>
                      <li><a href="#">Sample Menu #2</a></li>
                    </ul>
                  </li>
                </ul>
              </li>
              <li class="menu-item-has-children">
                <a href="#">Contact</a>
                <ul class="sub-menu">
                  <li><a href="contact.html">Contact 1</a></li>
                  <li><a href="contact-2.html">Contact 2</a></li>
                </ul>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <div id="back2top"><i class="fa fa-angle-up"></i></div>
    <div class="loader"></div>
    <div class="page-wrap">
      <!--section-->
      <div class="ps-section--hero">
        <img src="{% static 'images/hero/01.jpg' %}" alt="" />
        <div class="ps-section__content text-center">
          <h3 class="ps-section__title">TAIPING BAKERY</h3>
          <div class="ps-breadcrumb">
            <ol class="breadcrumb">
              <li><a href="{% url 'index' %}">Home</a></li>
              <li class="active">Cart</li>
            </ol>
          </div>
        </div>
      </div>
      <div class="container">
        <div class="ps-about__sign text-center mb-30 mt-40">
            <h1>Thank you</h1>
            <p>
              Your order has been successfully completed.
            </p>
        </div>

      </div>
    </div>
          <!--footer-->
          <footer class="ps-footer">
            <div class="container">
              <div class="row">
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 ">
                      <div class="ps-widget ps-widget--footer ps-widget--payment">
                        <div class="ps-widget__header">
                          <h3 class="ps-widget__title">PAYMENTS ACCEPTED</h3>
                        </div>
                        <div class="ps-widget__content">
                          <ul>
                            <li><a href="#"><img src="images/payment/1.png" alt=""></a></li>
                            <li><a href="#"><img src="images/payment/2.png" alt=""></a></li>
                            <li><a href="#"><img src="images/payment/3.png" alt=""></a></li>
                            <li><a href="#"><img src="images/payment/4.png" alt=""></a></li>
                            <li><a href="#"><img src="images/payment/5.png" alt=""></a></li>
                          </ul>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 ">
                      <div class="ps-widget ps-widget--footer ps-widget--worktime">
                        <div class="ps-widget__header">
                          <h3 class="ps-widget__title">WORK TIME</h3>
                        </div>
                        <div class="ps-widget__content">
                          <p><strong>Monday - Friday</strong> 8:00 am - 8:30 pm</p>
                          <p><strong>Satuday - Sunday</strong>10:00 am - 16:30 pm</p>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 ">
                      <div class="ps-widget ps-widget--footer ps-widget--order">
                        <div class="ps-widget__header">
                          <h3 class="ps-widget__title">ORDERS AND RETURNS</h3>
                        </div>
                        <div class="ps-widget__content">
                              <ul class="ps-list--line">
                                <li><a href="#">Order</a></li>
                                <li><a href="#">Shipping</a></li>
                                <li><a href="#">Policy Return Policy</a></li>
                                <li><a href="#">Payments</a></li>
                              </ul>
                        </div>
                      </div>
                    </div>
                    <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 ">
                      <div class="ps-widget ps-widget--footer ps-widget--connect">
                        <div class="ps-widget__header">
                          <h3 class="ps-widget__title">CONNECT US</h3>
                        </div>
                        <div class="ps-widget__content">
                              <ul class="ps-widget__social">
                                <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="#"><i class="fa fa-google"></i></a></li>
                                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                              </ul><a href="#"><img src="images/app.jpg" alt=""></a>
                          <p>@2021 Design by<a href="#"> Alena Studio</a>.</p>
                        </div>
                      </div>
                    </div>
              </div>
            </div>
          </footer>
        </div>
        <!-- JS Library-->
        <script
          type="text/javascript"
          src="{% static 'plugins/jquery/dist/jquery.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/bootstrap/dist/js/bootstrap.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/owl-carousel/owl.carousel.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/overflow-text.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/masonry.pkgd.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/imagesloaded.pkgd.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/jquery-bar-rating/dist/jquery.barrating.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/jquery-nice-select/js/jquery.nice-select.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/Magnific-Popup/dist/jquery.magnific-popup.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/moment.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/slick/slick/slick.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/gmap3.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/lightGallery-master/dist/js/lightgallery-all.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="https://maps.googleapis.com/maps/api/js?key=AIzaSyB458d7lg9ttCaCfXKPEf-LBAebMMw5RaU&amp;region=GB"
        ></script>
        <!-- Revolution - slider-->
        <script
          type="text/javascript"
          src="{% static 'plugins/revolution/js/jquery.themepunch.tools.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/revolution/js/jquery.themepunch.revolution.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/revolution/js/extensions/revolution.extension.video.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/revolution/js/extensions/revolution.extension.slideanims.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/revolution/js/extensions/revolution.extension.layeranimation.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/revolution/js/extensions/revolution.extension.navigation.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/revolution/js/extensions/revolution.extension.parallax.min.js' %}"
        ></script>
        <script
          type="text/javascript"
          src="{% static 'plugins/revolution/js/extensions/revolution.extension.actions.min.js' %}"
        ></script>
        <!-- Custom scripts-->
        <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  </body>
</html>